### PR TITLE
Development

### PR DESCRIPTION
**Pull request by 300ms**

### CODE REVIEW

**Review by uche-inyama — COMMENTED** [review]
### Pull request under review by Inyama, Uchechukwu Henry (TSE)

**Review by uche-inyama — APPROVED** [review]
### Nice work team :raised_hands: 
Just few changes:
- [x] Ensure your Html file passes the validation test.
- [x] Use the ```<main></main>```  tag to enclose the content of the webpage, between the naviagation tag and the footer tag.   Adhere to semantic html guideline
- [x] Your webpage moves along with the mouse/cursor when you move your mouse around. But, it should be static.
- [x] **Footer**, It should have a fixed position (it sticks to the bottom part of the screen).

#### If you need assistance, you can reach me slack @Inyama, Uchechukwu Henry for clarifcations


### Implement these changes, and submit another code review form. You are almost there :fire: :medal_sports:

**Comment by samgaco** [comment]
#### Hi @300ms and @Luzaks :hand: 

* Fix the remaining errors given to you by the [validator](https://validator.w3.org) when uploading the index file.
* There is a horizontal scrolling bar that shouldn't be showing. Try to address that too.

#### Please :pray: work on these two points and submit back for another code review once you are done. Regards!! :muscle:

**Comment by 300ms** [comment]
Hey @samgaco, ^^
Yes it is me again ^^ Seems like we are really having troubles because of "Direct Input" validation. Because we don't get errors when we use that way for validation. Thanks for review, we will try to fix both problems soon ^^

> 
> #### Hi @300ms and @Luzaks ✋
> 
>     * Fix the remaining errors given to you by the [validator](https://validator.w3.org) when uploading the index file.
> 
>     * There is a horizontal scrolling bar that shouldn't be showing. Try to address that too.
> 
> 
> #### Please 🙏 work on these two points and submit back for another code review once you are done. Regards!! 💪

**Review by stratospherique — APPROVED** [review]
### Great work @Luzaks , Your project is approved :100: . You can merge to master :+1: :+1: . Keep up the good work :muscle:

**Pull request merged**
